export const SEARCH_RESULTS = "SEARCH_RESULTS";
export const INCREMENT_OFFSET = "INCREMENT_OFFSET";
export const RESET_SEARCH = "RESET_SEARCH";
export const SET_RANDOM = "SET_RANDOM";
export const CLEAR_RANDOM = "CLEAR_RANDOM";
export const MENU_SWITCH = "MENU_SWITCH";
